### ISSUE TITLE
SingleGAN paper and code

### ISSUE THREAD

**Issue by Xiaoming-Yu** [nightrome/really-awesome-gan#12]
Thanks for your list of GANs.
Please consider adding our paper: [SingleGAN: Image-to-Image Translation by a Single-Generator Network using Multiple Generative Adversarial Learning](https://arxiv.org/abs/1810.04991).
Code: [https://github.com/Xiaoming-Yu/SingleGAN](https://github.com/Xiaoming-Yu/SingleGAN)
Thanks

**Comment by nightrome** [comment]
Done.
