### ISSUE TITLE
A-SRGAN and Step-Up GAN

### ISSUE THREAD

**Issue by harsh306** [nightrome/really-awesome-gan#17]
Thank you for the awesome list. Please consider adding our work. 
**A-SRGAN**: is an attentional Super-resolution GAN applied to create HD images.
https://arxiv.org/abs/1812.04821

On training strategy, **Step-Up GAN** is a data continuation approach which was part of these works:
1. https://digitalcommons.wpi.edu/etd-theses/1256/
2. https://www.wpi.edu/news/announcements/data-science-ms-thesis-presentation-xiaozhou-zou

**Comment by nightrome** [comment]
Done :-).

**Comment by harsh306** [comment]
Thank you for adding A-SRGAN, actually, Step-Up GAN is a different work. And the two thesis links belong to Step-Up GAN. Can you please update and add Step-Up GAN too.

**Comment by nightrome** [comment]
So what's the full paper title of Step-up GAN?
