### ISSUE TITLE
Sorting the paper links

### ISSUE THREAD

**Issue by g7shah** [nightrome/really-awesome-gan#18]
It's good that you collected all the links and posted them at one place, but it would've been much better if you mentioned the year that paper was published on the side. As well as it would've been better if you clustered them according to the application (Like this research papers deals with images, etc).
I am working on that, it would be my pleasure if you give me permission to commit it on your repo.

Regards,
Gunjan Shah

**Comment by nightrome** [comment]
Hi, adding the year may be useful. Whether it deals with images or not is hard to categorize. First of all almost all GAN papers deal with images and second some could deal with different modalities as they're discussing theoretical insights, rather than practical improvements.
