### ISSUE TITLE
Ideas about describing each GAN

### ISSUE THREAD

**Issue by DonaldTsang** [nightrome/really-awesome-gan#23]
As noted in https://github.com/kozistr/Awesome-GANs/issues/14 and https://github.com/kozistr/Awesome-GANs/issues/18 I would like to request help in regards to collecting GANs. If it is possible I would like to ask for help as to:
- formalize the meta-structure of GANs outside of specific generators and discriminators (should have)
- visualize the meta-structures of GANs in a way that is easy to understand (see pic below) (should have)
- turn the GAN meta-structure into a Python class that can allow for hot-swappable generators and discriminators (could have)
- update Awesome-GANs with more GAN models and architectures through Python/Tensorflow (could have)

Here is the type of thing that may be useful for understanding GANs
![](https://www.researchgate.net/profile/Kunfeng_Wang/publication/319869547/figure/fig3/AS:660911190716417@1534584915656/Computation-procedures-and-structures-of-some-GAN-variants-a-GAN-1-WGAN-31.png)

**Comment by nightrome** [comment]
Unfortunately I haven't been working with GANs in a while, so I will be of little use. The project however sounds awesome and I'd be happy to link to it at the top of my page.
